### ISSUE TITLE
this lib does not make random salt

### ISSUE THREAD

**Issue by mozartilize** [wuriyanto48/go-pbkdf2#1]
and it causes hashpassword always generate the same result

take a look at https://flaviocopes.com/go-random/

**Comment by wuriyanto48** [comment]
thank you @mozartilize , i didn't realize until i test myself

**Comment by wuriyanto48** [comment]
fix
https://github.com/wuriyanto48/go-pbkdf2/commit/40609df224190897582ea6815eeac69c0854ae3b
